#config/packages/fos_rest.yaml
fos_rest:
  body_listener: true
  param_fetcher_listener: true
  view:
    view_response_listener: "force"
    formats:
      json: true
  format_listener:
    rules:
      - {
          path: ^/api,
          prefer_extension: true,
          fallback_format: json,
          priorities: [json],
        }
  exception:
    enabled: true
    # codes:
    #   'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
    # messages:
    #   'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
